### ISSUE TITLE
Cache should be deleted on change permalink structure

### ISSUE THREAD

**Issue by etruel** [Etruel-Developments/flash-cache#14]
**Could use this action on [set_permalink_structure function](https://github.com/WordPress/wordpress-develop/blob/28f10e4af559c9b4dbbd1768feff0bae575d5e78/src/wp-includes/class-wp-rewrite.php#L1934) to delete cache on change structure:** 

```
/**
 * Fires after the permalink structure is updated.
 *
 * @since 2.8.0
 *
 * @param string $old_permalink_structure The previous permalink structure.
 * @param string $permalink_structure     The new permalink structure.
 */
do_action( 'permalink_structure_changed', $old_permalink_structure, $permalink_structure );

```
Found at:
https://github.com/WordPress/wordpress-develop/blob/28f10e4af559c9b4dbbd1768feff0bae575d5e78/src/wp-includes/class-wp-rewrite.php#L1949

**Comment by gerarjos14** [comment]
Solucionated
