### ISSUE TITLE
Not creating flash_cache directory

### ISSUE THREAD

**Issue by etruel** [Etruel-Developments/flash-cache#21]
The tests were on netmdp.com website
The folder flash_cache was not created.  

Some particularities of this site: 

- the domain includes 'www'
- Using apache, PHP 7.3
- Wordpress is installed in a subdirectory folder:  "Netmdp". (Así con la N en mayusculas) 
- Seems it's taken wrong the path: error_log( **_/flash_cache/www.netmdp.com/_** cache_debug.log ): failed to open stream: No such file or directory in
- With lock by file, always persists Current Disk Usage: 0 B
- With lock by DB, seems to be working fine because Current Disk Usage is growing up like normal

**Comment by etruel** [comment]
PHP updated to 7.4

**Comment by sniuk** [comment]
@etruel  @manuelge  la configuración de NetMdp tiene un index.php que se hace pasar por el index.php del wordpress, esto nunca lo había mapeado como una posibilidad y estaba fallando la ruta de creación de cache, con algunos ajustes se logro dar compatibilidad.

@manuelge por favor probar lo siguiente:

- Que el funcionamiento este correcto en NetMdp.com
- Que el plugin sigue funcionando bien en sitios web normales de wordpress en los diferentes tipos de cache ob y curl para html y php (En pocas volver a testear todo)

**Comment by etruel** [comment]
fixed on 3.0.2
