### ISSUE TITLE
New option on settings to avoid cache searches URls

### ISSUE THREAD

**Issue by etruel** [Etruel-Developments/flash-cache#30]
NOTE: This is in the pattern.  Could be made from it instead of a new option ?

By default cache all searches on /search folder.  
Some strings from searches could be really complicated and bots can make infinites queries.  

With this option we can avoid create cache folders from searches.  And Search can be executed in normal way from WP.

**Comment by etruel** [comment]
[Sat Apr 15 10:17:21.051864 2023] [proxy_fcgi:error] [pid 20050] [client XXX.XXX.171.11:40248] AH01071: Got error '
PHP message: PHP Warning:  file_put_contents(/cache_dir/netmdp.com/search/%EA%B8%88%EC%B2%9C%EB%84%A4%EC%9D%B4%EB%B2%84%EA%B2%80%EC%83%89%EA%B4%91%EA%B3%A0%E3%80%94%EB%9D%BC%EC%9D%B8%20@UY454%E3%80%95%20%EC%9C%A0%EB%A6%AC%EB%A7%89%EC%BD%94%ED%8C%85%EB%84%A4%EC%9D%B4%EB%B2%84%EA%B4%91%EA%B3%A0%20%EA%B8%88%EC%B2%9C%EB%84%A4%EC%9D%B4%EB%B2%84%EA%B4%91%EA%B3%A0%E2%84%A6%EC%9C%A0%EB%A6%AC%EB%A7%89%EC%BD%94%ED%8C%85%EB%84%A4%EC%9D%B4%EB%B2%84%EA%B4%91%EA%B3%A0%E2%92%BB%EC%9C%A0%EB%A6%AC%EB%A7%89%EC%BD%94%ED%8C%85%20FEA/can_create_cache.txt): failed to open stream: File name too long in /var/www/clients/client1/web55/web/Netmdp/wp-content/plugins/flash-cache/includes/process.php on line 49

PHP message: PHP Warning:  fopen(/cache_dir/netmdp.com/search/%EA%B8%88%EC%B2%9C%EB%84%A4%EC%9D%B4%EB%B2%84%EA%B2%80%EC%83%89%EA%B4%91%EA%B3%A0%E3%80%94%EB%9D%BC%EC%9D%B8%20@UY454%E3%80%95%20%EC%9C%A0%EB%A6%AC%EB%A7%89%EC%BD%94%ED%8C%85%EB%84%A4%EC%9D%B4%EB%B2%84%EA%B4%91%EA%B3%A0%20%EA%B8%88%EC%B2%9C%EB%84%A4%EC%9D%B4%EB%B2%84%EA%B4%91%EA%B3%A0%E2%84%A6%EC%9C%A0%EB%A6%AC%EB%A7%89%EC%BD%94%ED%8C%85%EB%84%A4%EC%9D%B4%EB%B2%84%EA%B4%91%EA%B3%A0%E2%92%BB%EC%9C%A0%EB%A6%AC%EB%A7%89%EC%BD%94%ED%8C%85%20FEA/can_create_cache.txt): failed to open stream: File name too long in /Netmdp/wp-content/plugins/flash-cache/includes/process.php on line 51

PHP message: PHP Warning:  flock() expects parameter 1 to be resource, bool given in /Netmdp/wp-content/plugins/flash-cache/includes/process.php on line 56

PHP message: PHP Warning:  flock() expects parameter 1 to be resource, bool given in /Netmdp/wp-content/plugins/flash-cache/includes/process.php on line 126

PHP message: PHP Warning:  fclose() expects parameter 1 to be resource, bool given in /Netmdp/wp-content/plugins/flash-cache/includes/process.php on line 127'

**Comment by manuelge** [comment]
I leave you the HTML code for the new option, this code must be added after the div of the "Search Pages" option.

Verify and correct the checkbox name.

`<div style="margin-left:20px">
	<div class="checkbox-group">
		<input type="checkbox" value="1" name="page_type[search]" checked="checked">Avoid cache searches
	</div>
</div>`
