### ISSUE TITLE
Error with path at the moment of make the cache files

### ISSUE THREAD

**Issue by gerarjos14** [Etruel-Developments/flash-cache#34]
When the cache is created with the permalinks "plain text", "numeric" and probably "custom structure" the files isn't maked and saved
![imagen_2023-04-18_224448401](https://user-images.githubusercontent.com/88218380/232953397-595e8f2a-d2d3-427a-b6c6-164b52b8f3f3.png)
![imagen_2023-04-18_224531412](https://user-images.githubusercontent.com/88218380/232953488-cf05aeed-58cb-4a62-a640-fe01f98c2d77.png)
![imagen_2023-04-18_224552653](https://user-images.githubusercontent.com/88218380/232953541-4f33d106-233e-4ad8-96ac-a090fde3feb1.png)

**Comment by etruel** [comment]
A requirement for Flash Cache is to use permalinks, because it work with the path structure to make the caches. 
So it would not be an issue to fix.
**ANYWAY, we should add a notice and avoid enable cache if the first option "Plain" of Settings, Permalink is selected.**
