### ISSUE TITLE
Fatal Error in the Optimize Scripts function

### ISSUE THREAD

**Issue by manuelge** [Etruel-Developments/flash-cache#44]
The error is generated only when the **"Include SEO & Social scripts in optimized file"** feature is disabled.

WP debug mode must be enabled to see the debug.log file.

**PHP Fatal error:  Uncaught Error: Call to undefined function get_excludedPlatforms()** in /var/www/clients/client1/web112/web/wp-content/plugins/flash-cache/includes/optimize_scripts.php:298
Stack trace:
#0 /var/www/clients/client1/web112/web/wp-content/plugins/flash-cache/includes/optimize_scripts.php(191): flash_cache_optimize_scripts::excludeSocialScripts()
#1 /var/www/clients/client1/web112/web/wp-content/plugins/flash-cache/includes/optimize_scripts.php(46): flash_cache_optimize_scripts::checkExcludes()
#2 /var/www/clients/client1/web112/web/wp-includes/class-wp-hook.php(308): flash_cache_optimize_scripts::init_process()
#3 /var/www/clients/client1/web112/web/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#4 /var/www/clients/client1/web112/web/wp-content/plugins/flash-cache/includes/process.php(648): apply_filters()
#5 /var/www/clients/client1/web112/web/wp-content/plugins/flash-cache/includes/process.php(608): flash_cache_process::create_cache_ob_html()
#6 /var/www/clients/client1/web112/web/wp-content/plugins/flash-cache/includes/process.php(582): flash_cache_process::create_cache_from_ob()
#7 [internal function]: flash_cache_process::ob_callback()
#8 /var/www/clients/client1/web112/web/wp-includes/functions.php(5309): ob_end_flush()
#9 /var/www/clients/client1/web112/web/wp-includes/class-wp-hook.php(308): wp_ob_end_flush_all()
#10 /var/www/clients/client1/web112/web/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#11 /var/www/clients/client1/web112/web/wp-includes/plugin.php(517): WP_Hook->do_action()
#12 /var/www/clients/client1/web112/web/wp-includes/load.php(1144): do_action()
#13 [internal function]: shutdown_action_hook()
#14 {main}
  thrown in /var/www/clients/client1/web112/web/wp-content/plugins/flash-cache/includes/optimize_scripts.php on line 298

**Comment by gerarjos14** [comment]
Fixed
