### ISSUE TITLE
Problems with css and cache

### ISSUE THREAD

**Issue by manuelge** [Etruel-Developments/flash-cache#60]
The problem occurs on some pages of a website.

Analyzing the generated cache files I could see that it is not saving all the site's CSS code but a part of it.

In this case the style.min.css file included in the theme was not saved in the generated CSS, that's why it breaks the site design.

This problem could be related to the moment of creating a new post, when the function to delete/generate the new cache is executed.

**Comment by etruel** [comment]
The error could not be reproduced.
